name: lint

on:
  workflow_call:
    inputs:
      working-directory:
        required: true
        type: string
        description: "From which folder this pipeline executes"
      node-version:
        required: true
        type: string
        description: "Node.js version to use"

env:
  WORKDIR: ${{ inputs.working-directory == '' && '.' || inputs.working-directory }}

jobs:
  build:
    name: "lint #node${{ inputs.node-version }}"
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js ${{ inputs.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}
          cache: "npm"

      - name: Install dependencies
        working-directory: ${{ inputs.working-directory }}
        run: |
          npm ci

      - name: Build TypeScript
        working-directory: ${{ inputs.working-directory }}
        run: |
          npm run build

      - name: Lint TypeScript code
        working-directory: ${{ inputs.working-directory }}
        run: |
          npx tsc --noEmit --strict
          echo "✅ TypeScript compilation check passed"
