name: test

on:
  workflow_call:
    inputs:
      working-directory:
        required: true
        type: string
        description: "From which folder this pipeline executes"
      node-version:
        required: true
        type: string
        description: "Node.js version to use"

jobs:
  build:
    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}
    runs-on: ubuntu-latest
    timeout-minutes: 20
    name: "test #node${{ inputs.node-version }}"
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js ${{ inputs.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}
          cache: 'npm'

      - name: Install dependencies
        shell: bash
        run: npm ci

      - name: Build TypeScript
        shell: bash
        run: npm run build

      - name: Run tests
        shell: bash
        run: npm test

      - name: Test CLI functionality
        shell: bash
        run: |
          echo "Testing CLI help output..."
          node dist/cli.js --help
          echo "✅ CLI help works"
          
          echo "Testing CLI version output..."
          node dist/cli.js --version
          echo "✅ CLI version works"

      - name: Test MCP tools functionality
        shell: bash
        run: |
          echo "Testing MCP tools..."
          echo '{"jsonrpc": "2.0", "id": 1, "method": "tools/list"}' | timeout 10s node dist/cli.js --urls "Test:https://example.com/llms.txt" --transport stdio
          echo "✅ MCP tools work"
